### ISSUE TITLE
Chrome code coverage fails on Windows

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/coverage#301]
Running the tests is fine using `test` but when `--coverage` flag is added the following stack trace is generated. The output directory is created but nothing ends up in it.

This is on `2.8.0-dev.17.0 (dev)` with latest test.

```
This is an unexpected error. Please file an issue at http://github.com/dart-lang/test
with the stack trace and instructions for reproducing the error.
Unhandled exception:
Invalid argument(s): Illegal character in path
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1732:11)
dart-lang/test#1      _Uri._makeWindowsFileUrl (dart:core/uri.dart:1796:7)
dart-lang/test#2      new _Uri.file (dart:core/uri.dart:1700:11)
dart-lang/test#3      Chrome._sourceUriProvider (package:test/src/runner/browser/chrome.dart:131:15)
dart-lang/test#4      parseChromeCoverage (package:coverage/src/chrome.dart:59:44)
<asynchronous suspension>
dart-lang/test#5      Chrome.gatherCoverage (package:test/src/runner/browser/chrome.dart:109:26)
<asynchronous suspension>
dart-lang/test#6      BrowserManager.load.<anonymous closure>.<anonymous closure> (package:test/src/runner/browser/browser_manager.dart:247:49)
dart-lang/test#7      RunnerSuite.gatherCoverage (package:test_core/src/runner/runner_suite.dart:85:43)
dart-lang/test#8      writeCoverage (package:test_core/src/runner/coverage.dart:16:51)
dart-lang/test#9      Engine.run.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/engine.dart:275:40)
<asynchronous suspension>
dart-lang/test#10     Engine.run.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/engine.dart)
dart-lang/test#11     Engine.run.<anonymous closure> (package:test_core/src/runner/engine.dart:279:8)
dart-lang/test#12     _rootRunUnary (dart:async/zone.dart:1155:38)
dart-lang/test#13     _CustomZone.runUnary (dart:async/zone.dart:1048:19)
dart-lang/test#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:950:7)
dart-lang/test#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
dart-lang/test#16     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
dart-lang/test#17     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
dart-lang/test#18     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
dart-lang/test#19     _rootRun (dart:async/zone.dart:1147:13)
dart-lang/test#20     _CustomZone.run (dart:async/zone.dart:1040:19)
dart-lang/test#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:966:23)
dart-lang/test#22     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
dart-lang/test#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
dart-lang/test#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
dart-lang/test#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by grouma** [comment]
Given that

> The output directory is created but nothing ends up in it.

I'm going to move this issue over to `package:coverage`. It's unlikely the root cause is in `package:test`.

**Comment by donny-dont** [comment]
Using `http` as a test in this case since there are dart vm and browser tests.

```
C:\Users\don\Documents\GitHub\http>pub upgrade
Resolving dependencies...
  _fe_analyzer_shared 1.0.3
  analyzer 0.39.4
  args 1.6.0
  async 2.4.1
  boolean_selector 2.0.0
  charcode 1.1.3
  collection 1.14.12
  convert 2.1.1
  coverage 0.13.9
  crypto 2.1.4
  csslib 0.16.1
  glob 1.2.0
  html 0.14.0+3
  http_multi_server 2.2.0
  http_parser 3.1.4
  io 0.3.3
  js 0.6.1+1
  logging 0.11.4
  matcher 0.12.6
  meta 1.1.8
  mime 0.9.6+3
  multi_server_socket 1.0.2
  node_interop 1.0.3
  node_io 1.0.1+2
  node_preamble 1.4.8
  package_config 1.9.3
  path 1.6.4
  pedantic 1.9.0
  pool 1.4.0
  pub_semver 1.4.4
  shelf 0.7.5
  shelf_packages_handler 2.0.0
  shelf_static 0.2.8
  shelf_web_socket 0.2.3
  source_map_stack_trace 2.0.0
  source_maps 0.10.9
  source_span 1.7.0
  stack_trace 1.9.3
  stream_channel 2.0.0
  string_scanner 1.0.5
  term_glyph 1.1.0
  test 1.14.2
  test_api 0.2.15
  test_core 0.3.3
  typed_data 1.1.6
  vm_service 4.0.0
  watcher 0.9.7+14
  web_socket_channel 1.1.0
  webkit_inspection_protocol 0.5.0+1
  yaml 2.2.0
No dependencies changed.
```

Its the -p Chrome tests that fail when gathering coverage. See the following run.

```
C:\Users\don\Documents\GitHub\http>pub run test -p chrome --coverage=coverage-chrome
00:12 +0: compiling test\html\streamed_request_test.dart
Compiled 9,214,105 characters Dart to 1,139,658 characters JavaScript in 11.9 seconds
Dart file C:\Users\don\AppData\Local\Temp\dart_test_282d6897-72dc-11ea-832c-94de806ce197\runInBrowser.dart compiled to JavaScript: ../../../AppData/Local/Temp/dart_test_282d6891-72dc-11ea-832c-94de806ce197/test_282d6893-72dc-11ea-832c-94de806ce197/streamed_request_test.dart.browser_test.dart.js

00:12 +0: compiling test\multipart_test.dart
Compiled 9,219,910 characters Dart to 1,217,060 characters JavaScript in 11.8 seconds
Dart file C:\Users\don\AppData\Local\Temp\dart_test_282d6899-72dc-11ea-832c-94de806ce197\runInBrowser.dart compiled to JavaScript: ../../../AppData/Local/Temp/dart_test_282d6891-72dc-11ea-832c-94de806ce197/test_282d6895-72dc-11ea-832c-94de806ce197/multipart_test.dart.browser_test.dart.js

00:12 +0: compiling test\html\client_test.dart
Compiled 9,214,133 characters Dart to 1,196,247 characters JavaScript in 12.1 seconds
Dart file C:\Users\don\AppData\Local\Temp\dart_test_282d6896-72dc-11ea-832c-94de806ce197\runInBrowser.dart compiled to JavaScript: ../../../AppData/Local/Temp/dart_test_282d6891-72dc-11ea-832c-94de806ce197/test_282d6892-72dc-11ea-832c-94de806ce197/client_test.dart.browser_test.dart.js

00:12 +0: compiling test\mock_client_test.dart
Compiled 9,218,330 characters Dart to 1,268,664 characters JavaScript in 12.1 seconds
Dart file C:\Users\don\AppData\Local\Temp\dart_test_282d6898-72dc-11ea-832c-94de806ce197\runInBrowser.dart compiled to JavaScript: ../../../AppData/Local/Temp/dart_test_282d6891-72dc-11ea-832c-94de806ce197/test_282d6894-72dc-11ea-832c-94de806ce197/mock_client_test.dart.browser_test.dart.js

00:15 +0: test\html\client_test.dart: #send a StreamedRequest
  Skip: Need to fix server tests for browser
00:15 +0 ~1: test\html\streamed_request_test.dart: contentLength works when it's set
  Skip: Need to fix server tests for browser
00:15 +0 ~2: test\html\streamed_request_test.dart: contentLength works when it's not set
  Skip: Need to fix server tests for browser
00:16 +8 ~3: test\multipart_test.dart: with a field name with newlines         Invalid argument(s): Illegal character in path
dart:core                                                    new _Uri.file
package:test/src/runner/browser/chrome.dart 131:15           Chrome._sourceUriProvider
package:coverage/src/chrome.dart 59:44                       parseChromeCoverage
package:test/src/runner/browser/chrome.dart 109:26           Chrome.gatherCoverage
package:test/src/runner/browser/browser_manager.dart 247:49  BrowserManager.load.<fn>.<fn>
package:test_core/src/runner/runner_suite.dart 85:43         RunnerSuite.gatherCoverage
package:test_core/src/runner/coverage.dart 16:51             writeCoverage
package:test_core/src/runner/engine.dart 275:40              Engine.run.<fn>.<fn>
package:test_core/src/runner/engine.dart                     Engine.run.<fn>.<fn>
package:test_core/src/runner/engine.dart 279:8               Engine.run.<fn>

This is an unexpected error. Please file an issue at http://github.com/dart-lang/test
with the stack trace and instructions for reproducing the error.
Unhandled exception:
Invalid argument(s): Illegal character in path
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1732:11)
#1      _Uri._makeWindowsFileUrl (dart:core/uri.dart:1796:7)
#2      new _Uri.file (dart:core/uri.dart:1700:11)
#3      Chrome._sourceUriProvider (package:test/src/runner/browser/chrome.dart:131:15)
#4      parseChromeCoverage (package:coverage/src/chrome.dart:59:44)
<asynchronous suspension>
#5      Chrome.gatherCoverage (package:test/src/runner/browser/chrome.dart:109:26)
<asynchronous suspension>
#6      BrowserManager.load.<anonymous closure>.<anonymous closure> (package:test/src/runner/browser/browser_manager.dart:247:49)
#7      RunnerSuite.gatherCoverage (package:test_core/src/runner/runner_suite.dart:85:43)
#8      writeCoverage (package:test_core/src/runner/coverage.dart:16:51)
#9      Engine.run.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/engine.dart:275:40)
<asynchronous suspension>
#10     Engine.run.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/engine.dart)
#11     Engine.run.<anonymous closure> (package:test_core/src/runner/engine.dart:279:8)
#12     _rootRunUnary (dart:async/zone.dart:1155:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1048:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:950:7)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#16     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#17     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#18     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#19     _rootRun (dart:async/zone.dart:1147:13)
#20     _CustomZone.run (dart:async/zone.dart:1040:19)
#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:966:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

The VM tests ran as expected this bug was specific to the Chrome platform.

```
C:\Users\don\Documents\GitHub\http>pub run test --coverage=coverage-io
Warning: You should set `SILENT_OBSERVATORY` to true when debugging the VM as it
will output the observatory URL by default.
This breaks the various reporter contracts.
To set the value define `DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true`.

00:00 +0: loading test\io\client_test.dart
00:01 +0: loading test\io\client_test.dart                                     Observatory listening on http://127.0.0.1:63633/Q4vbDm1IP3I=/
00:03 +19: loading test\io\client_test.dart


00:04 +29: loading test\io\streamed_request_test.dart
00:07 +32: loading test\mock_client_test.dart
00:08 +35: loading test\multipart_test.dart

00:09 +96: loading test\response_test.dart
00:10 +104: loading test\streamed_request_test.dart
00:12 +107: All tests passed!
```

**Comment by grouma** [comment]
@donny-dont can you depend on this branch and rerun your tests: https://github.com/dart-lang/test/pull/1210

I'd like to see what path is actually causing the failure.

Thanks!

**Comment by donny-dont** [comment]
The output was over 20 MBs so here's a couple error results. All of them are of the same form. A directory in the front then a file path to the cache.

```
Unable to parse path: test\html\file:///C:/Users/don/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/string_scanner-1.0.5/lib/src/span_scanner.dart
Unable to parse path: test\html\file:///C:/Users/don/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/source_span-1.7.0/lib/src/file.dart
```

**Comment by grouma** [comment]
@donny-dont can you rerun the test one last time with the latest changes to the branch? I believe it should work. If not there is additional logging which should be enough for me to figure out what's going on.

**Comment by donny-dont** [comment]
```
Unable to parse path: localhost:63083\rjJe7LMjhJKdJuKB0Tn241J%2B1hNwxuD%2B\test\file:///C:/Users/don/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/test_core-0.3.3/lib/src/runner/suite.dart
Provided sourceUrl: file:///C:/Users/don/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/test_core-0.3.3/lib/src/runner/suite.dart
Corresponding script: http://localhost:63083/rjJe7LMjhJKdJuKB0Tn241J%2B1hNwxuD%2B/test/request_test.dart.browser_test.dart.js
Unable to parse path: localhost:63083\rjJe7LMjhJKdJuKB0Tn241J%2B1hNwxuD%2B\test\file:///C:/Users/don/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/test_core-0.3.3/lib/src/runner/suite.dart
Provided sourceUrl: file:///C:/Users/don/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/test_core-0.3.3/lib/src/runner/suite.dart
Corresponding script: http://localhost:63083/rjJe7LMjhJKdJuKB0Tn241J%2B1hNwxuD%2B/test/request_test.dart.browser_test.dart.js
```
