### ISSUE TITLE
coverage tool fails on 1.3.2

### ISSUE THREAD

**Issue by albertodev01** [dart-lang/coverage#390]
Yesterday I was able to collect code coverage with `flutter test --coverage`. Today I upgraded to 1.3.2 and I get this error on my windows, mac and linux machines:

```bash
00:00 +0: loading C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\instantiation_test.dart                                                      00:01 +0: loading C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\instantiation_test.dart                                                      00:02 +0: loading C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\instantiation_test.dart                                                      00:02 +0: C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\instantiation_test.dart: Testing constructors of the classes Widgets constructors    00:02 +1: C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\instantiation_test.dart: Testing constructors of the classes Widgets constructors    00:03 +1: C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\instantiation_test.dart: Testing constructors of the classes Widgets constructors    00:03 +1: loading C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\localization\localization_test.dart                                          00:03 +1: C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\localization\localization_test.dart: Making sure that localization works on context  00:03 +2: C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\main_test.dart: Testing the entry point of the app Making sure that 'main()' doesn't 00:03 +3: C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\main_test.dart: Testing the entry point of the app Making sure that 'main()' doesn't 00:03 +4: C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\main_test.dart: Testing the entry point of the app Making sure that 'main()' doesn't 00:03 +5: C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\main_test.dart: Testing the entry point of the app Making sure that 'main()' doesn't 00:04 +5: C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\main_test.dart: Testing the entry point of the app Making sure that 'main()' doesn't 00:04 +6: C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\routes\error_page_test.dart: Testing the 'ErrorPage' widget Making sure that the widg00:04 +7: C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\routes\error_page_test.dart: Testing the 'ErrorPage' widget Making sure that the widg00:04 +8: C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\routes\home_page\card_container_test.dart: ... widget Making sure that the widget is 00:05 +9: C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\routes\home_page\home_contents_test.dart: ... widget Making sure that the widget is rendered        unhandled error during test:
C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\instantiation_test.dart
getSourceReport: (112) Service has disappeared
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1734:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2245:21)
#2      VmService.getSourceReport (package:vm_service/src/vm_service.dart:2040:7)
#3      _getAllCoverage (package:flutter_tools/src/test/coverage_collector.dart:254:52)
<asynchronous suspension>
#4      collect (package:flutter_tools/src/test/coverage_collector.dart:217:39)
<asynchronous suspension>
#5      Future.any.onValue (dart:async/future.dart:611:5)
<asynchronous suspension>

00:05 +9 -1: loading C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\instantiation_test.dart [E]                                               
  getSourceReport: (112) Service has disappeared
  package:vm_service/src/vm_service.dart 1734:45                 new _OutstandingRequest
  package:vm_service/src/vm_service.dart 2245:21                 VmService._call
  package:vm_service/src/vm_service.dart 2040:7                  VmService.getSourceReport
  package:flutter_tools/src/test/coverage_collector.dart 254:52  _getAllCoverage
  ===== asynchronous gap ===========================
  package:flutter_tools/src/test/coverage_collector.dart 217:39  collect
  ===== asynchronous gap ===========================
  dart:async/future.dart 611:5                                   Future.any.onValue

00:05 +10 -1: C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\routes\home_page\home_contents_test.dart: ... widget Making sure that the widget 00:05 +11 -1: C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\routes\home_page\card_container_test.dart: Golden tests Golden test - CardContainer             unhandled error during test:
C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\localization\localization_test.dart
getSourceReport: (112) Service has disappeared
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1734:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2245:21)
#2      VmService.getSourceReport (package:vm_service/src/vm_service.dart:2040:7)
#3      _getAllCoverage (package:flutter_tools/src/test/coverage_collector.dart:254:52)
<asynchronous suspension>
#4      collect (package:flutter_tools/src/test/coverage_collector.dart:217:39)
<asynchronous suspension>
#5      Future.any.onValue (dart:async/future.dart:611:5)
<asynchronous suspension>

00:05 +11 -2: loading C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example\test\localization\localization_test.dart [E]                                  
  getSourceReport: (112) Service has disappeared
  package:vm_service/src/vm_service.dart 1734:45                 new _OutstandingRequest
  package:vm_service/src/vm_service.dart 2245:21                 VmService._call
  package:vm_service/src/vm_service.dart 2040:7                  VmService.getSourceReport
  package:flutter_tools/src/test/coverage_collector.dart 254:52  _getAllCoverage
  ===== asynchronous gap ===========================
  package:flutter_tools/src/test/coverage_collector.dart 217:39  collect
  ===== asynchronous gap ===========================
  dart:async/future.dart 611:5                                   Future.any.onValue

```

It even fails if I try to follow the guide in the README.md file:

```bash
PS C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example> flutter pub global run coverage:test_with_coverage
Could not find bin\test_with_coverage.dart in package coverage.
pub finished with exit code 66
PS C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example> flutter pub global activate coverage
Package coverage is currently active at version 1.0.2.
Resolving dependencies...
+ args 2.3.1
+ collection 1.16.0
+ coverage 1.3.2
+ logging 1.0.2
+ package_config 2.0.2
+ path 1.8.2
+ source_maps 0.10.10
+ source_span 1.9.0
+ stack_trace 1.10.0
+ term_glyph 1.2.0
+ vm_service 8.3.0
Downloading coverage 1.3.2...
Downloading path 1.8.2...
Downloading source_span 1.9.0...
Building package executables...
Built coverage:run_and_collect.
Built coverage:collect_coverage.
Built coverage:format_coverage.
Built coverage:test_with_coverage.
Installed executables collect_coverage, format_coverage and test_with_coverage.
Warning: Pub installs executables into D:\flutter\.pub-cache\bin, which is not on your path.
You can fix that by adding that directory to your system's "Path" environment variable.
A web search for "configure windows path" will show you how.
Activated coverage 1.3.2.
PS C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example> flutter pub global run coverage:test_with_coverage
The Dart VM service is listening on http://127.0.0.1:8181/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A8181%2Fws
Could not find package `test` or file `test`
Unhandled exception:
ProcessException:
  Command: D:\flutter\bin\cache\dart-sdk\bin\dart.EXE run --pause-isolates-on-exit --disable-service-auth-codes --enable-vm-service=8181 test
#0      dartRun (file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/coverage-1.3.2/bin/test_with_coverage.dart:38:5)
<asynchronous suspension>
pub finished with exit code 255
```
I get this result on windows, max and linux with Flutter 3.0.1, Dart 2.17.1 and the latest coverage version

**Comment by albertodev01** [comment]
You can find logs [here](https://github.com/albertodev01/equations/actions/runs/2379499931) of CI runs failing too

**Comment by LongXiangGuo** [comment]
I have reproduce this issue both int dart 2.17.3 and dart 2.15.0 with coverage 1.3.2, it has the same issue.

## Version support( flutter  3.0.2 dart 2.17.3 ❌)
Dart SDK version: 2.17.3 (stable) (Wed Jun 1 11:06:41 2022 +0200) on "macos_x64"

jiodg45@jiodg45s-MacBook-Pro coverage_demo % dart pub global run coverage:test_with_coverage
The Dart VM service is listening on http://127.0.0.1:8181/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A8181%2Fws
Could not find package `test` or file `test`
Unhandled exception:
ProcessException: 
  Command: /Users/jiodg45/versions/master/bin/cache/dart-sdk/bin/dart run --pause-isolates-on-exit --disable-service-auth-codes --enable-vm-service=8181 test
#0      dartRun (file:///Users/jiodg45/.pub-cache/hosted/pub.flutter-io.cn/coverage-1.3.2/bin/test_with_coverage.dart:38:5)
<asynchronous suspension>

## Version support( flutter 2.8.0 dart 2.15.0 ❌)

```

jiodg45@jiodg45s-MacBook-Pro coverage_demo % pub global run coverage:test_with_coverage --branch-coverage --function-coverage
The top level `pub` command is deprecated. Use `dart pub` instead.
Setting VM flags failed: Unrecognized flags: branch-coverage
Unhandled exception:
ProcessException: 
  Command: /Users/jiodg45/versions/master/bin/cache/dart-sdk/bin/dart --branch-coverage run --pause-isolates-on-exit --disable-service-auth-codes --enable-vm-service=8181 test
#0      dartRun (file:///Users/jiodg45/.pub-cache/hosted/pub.flutter-io.cn/coverage-1.3.2/bin/test_with_coverage.dart:38:5)
<asynchronous suspension>
jiodg45@jiodg45s-MacBook-Pro coverage_demo % dart --branch-coverage run --pause-isolates-on-exit --disable-service-auth-codes --enable-vm-service=8181 test
Setting VM flags failed: Unrecognized flags: branch-coverage
jiodg45@jiodg45s-MacBook-Pro coverage_demo % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.8.0, on macOS 12.3.1 21E258 darwin-x64, locale
    en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (1 available)
    ! Error: US的iPhone is not connected. Xcode will continue when US的iPhone is
      connected. (code -13)

• No issues found!
jiodg45@jiodg45s-MacBook-Pro coverage_demo % dart --version
Dart SDK version: 2.15.0 (stable) (Fri Dec 3 14:23:23 2021 +0100) on "macos_x64"
```

[Test Demo](https://github.com/LongXiangGuo/coverage_demo)

**Comment by albertodev01** [comment]
> Your second set of errors seems unrelated to the first. Does C:\Users\AlbertoMiola\Desktop\Programmazione\Dart\equations\example\flutter_example have a test/ directory?

Sorry I thought I replied! Yes it has a `test` directory. I get the error on macOS as well on a fresh project.

> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.19043.1766], locale it-IT)
> [√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
> [√] Chrome - develop for the web
> [√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
> [√] Android Studio (version 2021.2)
> [√] IntelliJ IDEA Community Edition (version 2021.3)
> [√] Connected device (3 available)
> [√] HTTP Host Availability

> Dart SDK version: 2.17.3 (stable) (Wed Jun 1 11:06:41 2022 +0200) on "windows_x64"

I'm using the latest coverage version

**Comment by LongXiangGuo** [comment]
dart --branch-coverage run --pause-isolates-on-exit --disable-service-auth-codes --enable-vm-service=8181 test
Setting VM flags failed: Unrecognized flags: branch-coverage

**Comment by liamappelbe** [comment]
@LongXiangGuo Not quite sure what issue you're reporting, but branch coverage was only introduced in Dart VM version 2.17.0. Also, this bug is not specific to branch coverage.

@albertodev01 I'll see if I can reproduce the issue in an empty flutter project

**Comment by liamappelbe** [comment]
@albertodev01 I'm not able to reproduce this issue in an empty project on my mac, using the same version of Flutter and package:coverage. I just ran:

```bash
flutter create empty_app
cd empty_app
flutter test --coverage
```

Flutter's coverage system doesn't directly use package:coverage, so maybe this is a Flutter issue? You said this was triggered when you updated package:coverage to 1.3.2. How exactly did you update it?

**Comment by LongXiangGuo** [comment]
> @LongXiangGuo Not quite sure what issue you're reporting, but branch coverage was only introduced in Dart VM version 2.17.0. Also, this bug is not specific to branch coverage.
> 
> @albertodev01 I'll see if I can reproduce the issue in an empty flutter project

Very thanks, I will try the the dart version `2.17.0` for test.
