### ISSUE TITLE
format_coverage fails on coverage generated from tests run in dartium

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/coverage#60]
I've been able to successfully generate, format, and view coverage of tests run on the VM, but with browser tests it fails for me on the format step:

```
pub global run coverage:format_coverage --package-root=packages -i browser_coverage.json --lcov > browser_coverage.info
Unhandled exception:
Uncaught Error: FileSystemException: Cannot resolve symbolic links, path = '/Volumes/data/b/build/slave/dartium-mac-full-stable/build/src/dart/sdk/lib/html/html_common/css_class_set.dart' (OS Error: No such file or directory, errno = 2)
Stack Trace:
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:671)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:338)
#2      Resolver.resolveSymbolicLinks (package:coverage/src/resolver.dart:66)
#3      Resolver.resolve (package:coverage/src/resolver.dart:55)
#4      LcovFormatter.format.<anonymous closure> (package:coverage/src/formatter.dart:21)
#5      Future.forEach.<anonymous closure>.<anonymous closure> (dart:async/future.dart:336)
#6      Future.Future.sync (dart:async/future.dart:168)
#7      Future.forEach.<anonymous closure> (dart:async/future.dart:336)
#8      Future.Future.sync (dart:async/future.dart:168)
#9      Future.doWhile.<anonymous closure> (dart:async/future.dart:361)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1093)
#11     _RootZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1122)
#12     _RootZone.runUnary (dart:async/zone.dart:1155)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:567)
#15     _Future._completeWithValue (dart:async/future_impl.dart:358)
#16     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:412)
#17     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#18     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
```

Additionally, I was curious if there's a way to specify which files you actually care about for coverage? Or at least a way to exclude certain files. The test coverage I was able to generate/format/view includes coverage for tests and package files, but I'd rather just have the source files.

**Comment by cbracken** [comment]
Thanks for reporting -- this was resolved by 2d4cc9374165d4f503244ab703c997811f264ffe which will roll out in 0.6.3, sometime near the end of this week.

Re: restricting output -- will take a look at #67. Thanks!
