### ISSUE TITLE
Cannot resolve symbolic links,

### ISSUE THREAD

**Issue by rayk** [dart-lang/coverage#71]
Hi I have a few problems with formating my coverage.json file... Any ideas or points would be most helpful.

```bash
Rays-iMac-2:goongo rayk$ format_coverage -s /usr/local/opt/dart/libexec -p /Users/rayk/code/goongo -i coverage.json
Unhandled exception:
Uncaught Error: FileSystemException: Cannot resolve symbolic links, path = '/usr/local/opt/dart/libexec/lib/_internal/list.dart' (OS Error: No such file or directory, errno = 2)
Stack Trace:
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:671)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:338)
#2      Resolver.resolveSymbolicLinks (package:coverage/src/resolver.dart:66)
#3      Resolver.resolve (package:coverage/src/resolver.dart:44)
#4      PrettyPrintFormatter.format.<anonymous closure> (package:coverage/src/formatter.dart:55)
#5      Future.forEach.<anonymous closure>.<anonymous closure> (dart:async/future.dart:336)
#6      Future.Future.sync (dart:async/future.dart:168)
#7      Future.forEach.<anonymous closure> (dart:async/future.dart:336)
#8      Future.Future.sync (dart:async/future.dart:168)
#9      Future.doWhile.<anonymous closure> (dart:async/future.dart:361)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1093)
#11     _RootZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1122)
#12     _RootZone.runUnary (dart:async/zone.dart:1155)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#15     _Future._completeWithValue (dart:async/future_impl.dart:368)
#16     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#17     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#18     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
Rays-iMac-2:goongo rayk$ 
```

***And when I don't pass the symlink for the Sdk I get:

```bash
Rays-iMac-2:goongo rayk$ format_coverage -p /Users/rayk/code/goongo -i coverage.json
Unhandled exception:
Uncaught Error: FileSystemException: Cannot resolve symbolic links, path = '/Volumes/data/b/build/slave/dartium-mac-full-stable/build/src/dart/sdk/lib/html/html_common/css_class_set.dart' (OS Error: No such file or directory, errno = 2)
Stack Trace:
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:671)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:338)
#2      Resolver.resolveSymbolicLinks (package:coverage/src/resolver.dart:66)
#3      Resolver.resolve (package:coverage/src/resolver.dart:55)
#4      PrettyPrintFormatter.format.<anonymous closure> (package:coverage/src/formatter.dart:55)
#5      Future.forEach.<anonymous closure>.<anonymous closure> (dart:async/future.dart:336)
#6      Future.Future.sync (dart:async/future.dart:168)
#7      Future.forEach.<anonymous closure> (dart:async/future.dart:336)
#8      Future.Future.sync (dart:async/future.dart:168)
#9      Future.doWhile.<anonymous closure> (dart:async/future.dart:361)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1093)
#11     _RootZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1122)
#12     _RootZone.runUnary (dart:async/zone.dart:1155)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#15     _Future._completeWithValue (dart:async/future_impl.dart:368)
#16     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#17     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#18     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

**Comment by cbracken** [comment]
Thanks for reporting! This was resolved by 2d4cc9374165d4f503244ab703c997811f264ffe and will roll out in 0.6.3, which I'll look at cutting by end of week.

**Comment by rayk** [comment]
Hi guys looked at 0.6.this morning appears to the have same problems, but it seems more of the exceptions are being caught.

Let me cover it from the top again for you. BTW sorry for all the permutations... just wanted make sure it was not by fat figures. _Not after the award for most spammy bug report.._

Thanks in advance...

-Have managed to generate a coverage.json

```bash
-rw-r--r--   1 rayk  staff     177 May 17 14:27 CHANGELOG.md
-rw-r--r--   1 rayk  staff   34519 May 16 15:33 LICENSE
-rw-r--r--@  1 rayk  staff     818 May 17 14:23 README.md
drwxr-xr-x   3 rayk  staff     102 May 19 11:28 build
-rw-r--r--   1 rayk  staff  683385 May 19 13:28 coverage.json
drwxr-xr-x  13 rayk  staff     442 May 20 08:39 docs
drwxr-xr-x   2 rayk  staff      68 May 16 15:26 examples
drwxr-xr-x   5 rayk  staff     170 May 19 10:03 lib
drwxr-xr-x  77 rayk  staff    2618 May 21 10:06 packages
-rw-r--r--   1 rayk  staff    6097 May 21 10:06 pubspec.lock
-rw-r--r--   1 rayk  staff     845 May 21 10:06 pubspec.yaml
drwxr-xr-x@  5 rayk  staff     170 May 21 10:06 test
drwxr-xr-x@  8 rayk  staff     272 May 21 10:06 tool
drwxr-xr-x@  9 rayk  staff     306 May 21 10:06 web
Rays-iMac-2:goongo rayk$ pwd
/Users/rayk/code/goongo
```

-At this point, I do the following

```Rays-iMac-2:goongo rayk$ format_coverage --package-root= Users/rayk/code/goongo/lib -i coverage.json```

When I receive.

```bash
No input files given.

Usage: dart format_coverage.dart [OPTION...]

-s, --sdk-root        path to the SDK root
-p, --package-root    path to the package root
-i, --in              input(s): may be file or directory
-o, --out             output: may be file or stdout
                      (defaults to "stdout")

-j, --workers         number of workers
                      (defaults to "1")

-r, --pretty-print    convert coverage data to pretty print format
-l, --lcov            convert coverage data to lcov format
-v, --verbose         verbose output
-h, --help            show this help
```

- So probably passing the parameters wrong ~ so will try some other combo's:

I removed the space between..ott= User....

```bash
Rays-iMac-2:goongo rayk$ format_coverage --package-root=Users/rayk/code/goongo/lib -i coverage.json

Provided package root "Users/rayk/code/goongo/lib" is not directory.

Usage: dart format_coverage.dart [OPTION...]

-s, --sdk-root        path to the SDK root
```

-  Ok lets try's with the slash..

```bash
Rays-iMac-2:goongo rayk$ format_coverage --package-root=/Users/rayk/code/goongo/lib -i coverage.json
Unhandled exception:
Uncaught Error: FileSystemException: Cannot resolve symbolic links, path = '/Volumes/data/b/build/slave/dartium-mac-full-stable/build/src/dart/sdk/lib/html/html_common/css_class_set.dart' (OS Error: No such file or directory, errno = 2)
Stack Trace:
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:671)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:338)
..
.
```

- This time not passing the input file it appears happy with my package root, and just tells me no input files given... OK time to try those combinations.

```bash
Rays-iMac-2:goongo rayk$ format_coverage --package-root= /Users/rayk/code/goongo/lib

No input files given.

Usage: dart format_coverage.dart [OPTION...]

```

- Using -i coverage.json

```bash
Rays-iMac-2:goongo rayk$ format_coverage --package-root= /Users/rayk/code/goongo/lib -i coverage.json

No input files given.

Usage: dart format_coverage.dart [OPTION...]

-s, --sdk-root        path to the SDK root
-p, --package-root    path to the package root
```

- Trying --in

```bash
Rays-iMac-2:goongo rayk$ format_coverage --package-root= /Users/rayk/code/goongo/lib --i coverage.json

No input files given.

Usage: dart format_coverage.dart [OPTION...]
```

- Going to try what I think would be most intuitive 

```bash

Rays-iMac-2:goongo rayk$ pwd
/Users/rayk/code/goongo
Rays-iMac-2:goongo rayk$ format_coverage --package-root=/Users/rayk/code/goongo -i coverage.json
Unhandled exception:
Uncaught Error: FileSystemException: Cannot resolve symbolic links, path = '/Volumes/data/b/build/slave/dartium-mac-full-stable/build/src/dart/sdk/lib/html/html_common/css_class_set.dart' (OS Error: No such file or directory, errno = 2)
Stack Trace:
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:671)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:338)
```

- OK last time without the package, after I am running in that directory.

```bash
Rays-iMac-2:goongo rayk$ format_coverage -i coverage.json
Unhandled exception:
Uncaught Error: FileSystemException: Cannot resolve symbolic links, path = '/Volumes/data/b/build/slave/dartium-mac-full-stable/build/src/dart/sdk/lib/html/html_common/css_class_set.dart' (OS Error: No such file or directory, errno = 2)
Stack Trace:
#0      FileSystemEntity._
```

Just to confirm from .lockfile

```yaml
 coverage:
    description: coverage
    source: hosted
    version: "0.6.3"
```

I check the version of dart.... 

```bash
Dart VM version: 1.10.0 (Fri Apr 24 17:32:20 2015) on "macos_x64"
Rays-iMac-2:goongo rayk$ 
```

That looked ok. Finally paths

```bash
Rays-iMac-2:goongo rayk$ brew info dart
dart: stable 1.10.0, devel 1.11.0-dev.0.0
https://www.dartlang.org/
/usr/local/Cellar/dart/1.10.0 (230 files, 32M) *
  Built from source
From: https://github.com/dart-lang/homebrew-dart/blob/master/dart.rb
==> Caveats
Please note the path to the Dart SDK:
  /usr/local/opt/dart/libexec
Rays-iMac-2:goongo rayk$ 
````

Ok brew looks it has put in it the right place. The coverage.json I am assuming it is ok I have regenerated a few times now.. but here is a snippet

```json
{"type":"CodeCoverage","coverage":[{"source":"dart:core/errors.dart","script":{"type":"@Script","id":"libraries/0/scripts/dart%3Acore%2Ferrors.dart","name":"dart:core/errors.dart","kind":"source"},"hits":[]},{"source":"dart:core/errors.dart","script":{"type":"@Script","id":"libraries/0/scripts/dart%3Acore%2Ferrors.dart","name":"dart:core/errors.dart","kind":"source"},"hits":[514,0,515,0]},{"source":"dart:core/symbol.dart","script":{"type":"@Script","id":"libraries/0/scripts/dart%3Acore%2Fsymbol.dart","name":"dart:core/symbol.dart","kind":"source"},"hits":[]},{"source":"dart:core/errors.dart","script":{"type":"@Script","id":"libraries/0/scripts/dart%3Acore%2Ferrors.dart","name":"dart:core/errors.dart","kind":"source"},"hits":[207,0,218,0,239,0,266,0,267,0,284,0,285,0,287,0,312,0,314,0,317,0,319,0,332,0,339,0,340,0,341,0,344,0,345,0,346,0,347,0,348,0,352,0]},{"source":"dart:core-patch/regexp_patch.dart","script":{"type":"@Script","id":"libraries/0/scripts/dart%3Acore-patch%2Fregexp_patch.dart","name":"dart:core-patch/regexp_patch.dart","kind":"patch"},"hits":[250,2,252,8]},{"source":"dart:core/regexp.dart","script":{"type":"@Script","id":"libraries/0/scripts/dart%3Acore%2Fregexp.dart","name":"dart:core/regexp.dart","kind":"source"},"hits":[]},{"source":"dart
```

What I have on my global list....

```bash
Rays-iMac-2:goongo rayk$ pub global list
coverage 0.6.1
dart_style 0.1.8
dartdoc 0.0.1+10
githelp 1.2.0
grinder 0.7.0
test 0.12.1
Rays-iMac-2:goongo rayk$ 
```

Finally.... the dependencies

```bash

goongo 0.0.2

dependencies:
- intl 0.12.3 [args path analyzer petitparser]
- paper_elements 0.7.1 [web_components core_elements polymer_interop]
- polymer 0.16.3+2 [browser args initialize html barback code_transformers template_binding smoke path polymer_interop observe logging yaml source_span web_components source_maps analyzer polymer_expressions]
- quiver 0.21.3+1 [matcher]

dev dependencies:
- analyzer 0.25.0+1 [watcher path]
- args 0.13.0
- benchmark_harness 1.0.4 [browser]
- colorize 0.1.2
- coverage 0.6.3 [logging http args path]
- dart_style 0.1.8 [source_span args path analyzer]
- dartdoc 0.0.2 [markdown pub_cache quiver args http html mustache4dart intl cli_util path logging yaml analyzer]
- git 0.4.4+1 [which path bot]
- githelp 1.2.0 [intl args browser_detect console_log_handler logging logging_handlers validate]
- glob 1.0.4 [string_scanner path collection]
- grinder 0.7.1+1 [cli_util which args http_server ansicolor webkit_inspection_protocol glob unscripted]
- mockito 0.10.1 [test]
- path 1.3.5
- pubspec 0.0.1+4 [pub_semver yaml yamlicious path]
- semver 0.2.1 [string_scanner unittest]
- test 0.12.1 [shelf_static args crypto matcher barback pool stack_trace pub_semver shelf_web_socket path http_parser yaml shelf source_span string_scanner analyzer]
- text 0.0.7 [lists]
- unscripted 0.6.1+1 [supports_color mockable_filesystem args path collection ansicolor]

transitive dependencies:
- ansicolor 0.0.9
- barback 0.15.2+4 [stack_trace source_span pool collection path]
- bot 0.28.0
- browser 0.10.0+2
- browser_detect 1.0.3
- cli_util 0.0.1+2 [which path]
- code_transformers 0.2.9 [source_span cli_util barback source_maps path analyzer]
- collection 1.1.1
- console_log_handler 0.1.4 [logging browser logging_handlers]
- core_elements 0.7.1+2 [quiver web_components polymer polymer_interop]
- crypto 0.9.0
- csslib 0.12.0+1 [logging source_span args path]
- html 0.12.1+1 [source_span csslib utf]
- http 0.11.2 [stack_trace http_parser path]
- http_parser 0.0.2+6 [crypto string_scanner collection]
- http_server 0.9.5+1 [path mime]
- initialize 0.6.1 [dart_style path barback html code_transformers glob analyzer]
- lists 0.0.21
- logging 0.11.1
- logging_handlers 0.8.0 [logging intl]
- markdown 0.7.1+2
- matcher 0.12.0
- mime 0.9.3
- mockable_filesystem 0.0.3 [logging path]
- mustache4dart 1.0.10
- observe 0.13.1+1 [smoke path utf logging barback source_span code_transformers source_maps analyzer]
- petitparser 1.4.3
- polymer_expressions 0.13.1 [observe template_binding browser]
- polymer_interop 0.1.1 [barback web_components code_transformers]
- pool 1.0.1 [stack_trace]
- pub_cache 0.0.1+2 [pub_semver yaml path]
- pub_semver 1.2.0 [collection]
- shelf 0.6.1+2 [stack_trace http_parser path collection]
- shelf_static 0.2.2 [http_parser shelf mime]
- shelf_web_socket 0.0.1+2 [http_parser shelf]
- smoke 0.3.3+1 [logging barback analyzer]
- source_maps 0.10.1 [source_span path]
- source_span 1.1.2 [path]
- stack_trace 1.3.2 [path]
- string_scanner 0.1.3+1 [source_span path]
- supports_color 0.1.1
- template_binding 0.14.0+2 [observe web_components]
- unittest 0.11.6 [stack_trace]
- utf 0.9.0+2
- validate 1.4.2
- watcher 0.9.5 [stack_trace path]
- web_components 0.11.4+1 [html barback code_transformers path initialize analyzer]
- webkit_inspection_protocol 0.0.1+1
- when 0.2.0
- which 0.1.3 [when path]
- yaml 2.1.2 [source_span string_scanner path collection]
- yamlicious 0.0.1+2 [quiver]
```

**Comment by cbracken** [comment]
> `--package-root= Users/rayk/code/goongo/lib`

If you're using `--pretty-print` (the default) on `format_coverage`, then the `--package-root` option should refer to the package root of the package being covered. Generally speaking, that means the `packages` directory of the package being covered. There shouldn't be a space after the = sign.

Based on the above, it looks like what you want is:
`format_coverage --package-root=Users/rayk/code/goongo/packages -i coverage.json`

**Comment by rayk** [comment]
Thanks tut... and the work on coverage... All working find now...

**Comment by cbracken** [comment]
Good to hear!
